module.exports = {
    app:{
        packageName:'',
        versionCode:0,
        name:'即刻',
        appId:0
    },
    gameTips:{
        default:{
            text:'点击安装资讯神器-即刻，获取2轮游戏机会',
        },
        installed:{
            text:'点击获取2轮游戏机会，消除标题党，消除越多中奖概率越大！',
            color:'#f4986f'
        },
        gameing:{
            text:'躲避炮弹，消除标题党，消除越多中奖概率越大！'
        }
    }
}